import psycopg2
from loguru import logger
from typing import NoReturn

from utils import SingletonMeta


class DBManager(metaclass=SingletonMeta):
    def __init__(self, dbname: str = None, user: str = None,
                 password: str = None, host: str = None, port: int = None):
        self.dbname = dbname
        self.user = user
        self.password = password
        self.host = host
        self.port = port
        self.conn = self.connect()

    def connect(self):
        """Establishes connection to the database
        """
        try:
            self.conn = psycopg2.connect(
                dbname=self.dbname,
                user=self.user,
                password=self.password,
                host=self.host,
                port=self.port
            )
            return self.conn
        except psycopg2.Error as e:
            logger.error(f"DB connection error: {e}")

    def close(self) -> NoReturn:
        """Close connection to the database
        """
        self.conn.close()

    def execute(self, query: str) -> NoReturn:
        """Executes sql-query to database

        Args:
            query (str): sql query string
        """
        try:
            with self.conn.cursor() as cursor:
                cursor.execute(query)
        except psycopg2.Error as e:
            logger.error(f"Error executing query: {e}")

    def execute_file(self, filename: str) -> NoReturn:
        """Executes sql-query to database from file

        Args:
            filename (str): file with sql-query string
        """
        try:
            self.execute(open(f'./{filename}').read())
        except FileNotFoundError:
            logger.error(f"File {filename} not found")

    def init_tables(self) -> NoReturn:
        """Initialisation table function
        """
        self.execute_file('init_tables.sql')
        logger.info('Tables initialized')
        self.conn.commit()

    def get_images(self, page: int = 1, limit: int = 10) -> list[tuple]:
        """Get images datas list for js function on web-pages from the database

        Args:
            page (int): Current page number on web-page. Defaults to 1.
            limit (int): Image count on one page. Defaults to 10.

        Returns:
            list[tuple]: image list
        """
        offset = (page - 1) * limit
        logger.info(f'Try to get images with offset {offset}')
        with self.connect().cursor() as cursor:
            cursor.execute(
                "SELECT * FROM images "
                "ORDER BY upload_time DESC LIMIT %s OFFSET %s",
                (limit, offset,))
            return cursor.fetchall()

    def add_image(self, filename: str, original_name: str,
                  length: int, ext: str) -> NoReturn:
        """Add image data to the database

        Args:
            filename (str): image filename generated by app
            original_name (str): image original filename
            length (int): image file size
            ext (str): image file extension
        """
        logger.info(f"Try to add image {filename}")
        with self.conn.cursor() as cursor:
            cursor.execute("INSERT INTO images "
                           "(filename, original_name, size, file_type)"
                           "VALUES (%s, %s, %s, %s)",
                           (filename, original_name, length, ext))
            self.conn.commit()

    def clear_images(self) -> NoReturn:
        with self.conn.cursor() as cursor:
            cursor.execute("DELETE FROM images")
        self.conn.commit()

    def delete_image(self, filename: str) -> NoReturn:
        """Removes image data from the database

        Args:
            filename (str): image file name for delete
        """
        logger.info(f'Try to delete image {filename}')
        try:
            with self.conn.cursor() as cursor:
                cursor.execute(
                    "DELETE FROM images WHERE filename = %s", (filename,))
            self.conn.commit()
        except psycopg2.Error as e:
            logger.error(f"Error deleting image: {e}")
